import { View, Text } from 'react-native'
import React from 'react'

const Home = () => {
  return (
    <View>
      <Text className='text-orange-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero nesciunt laudantium obcaecati, facilis maxime ex consectetur rerum ea exercitationem assumenda voluptas facere quia ipsam soluta omnis ullam fuga, quam ut! Repudiandae totam dolore, neque mollitia labore quibusdam in enim praesentium omnis illum. Architecto eaque expedita deserunt nobis recusandae ut voluptatibus iusto? Facilis sequi reiciendis eveniet, reprehenderit eos sunt culpa alias velit nisi qui ipsum dolores numquam, quas in quia vero? Corrupti minima illum maiores exercitationem quia blanditiis impedit eius? Beatae odit deleniti expedita corrupti provident perferendis quae necessitatibus corporis harum delectus. Mollitia modi beatae quod architecto hic explicabo doloribus, aliquam voluptates aliquid, labore nulla assumenda molestiae ex officiis voluptate, ullam similique totam quis quae vitae id eaque? Numquam deleniti veniam, enim molestiae qui eos ipsam sint obcaecati illo vel nesciunt tempore quos, nihil nobis quae. Velit quisquam quae voluptatum saepe iste, neque facere. Veritatis commodi magnam aliquid quam error laborum, unde alias temporibus eos deleniti sunt beatae quas obcaecati voluptatum voluptas illo doloribus, voluptates amet. Sequi omnis enim atque tenetur explicabo, praesentium neque laudantium quis optio porro deserunt commodi distinctio soluta in harum maiores. Rem dicta optio corrupti eligendi cupiditate iste, saepe, unde temporibus ducimus obcaecati rerum itaque suscipit! Libero!</Text>

      <Text className='text-yellow-200'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero nesciunt laudantium obcaecati, facilis maxime ex consectetur rerum ea exercitationem assumenda voluptas facere quia ipsam soluta omnis ullam fuga, quam ut! Repudiandae totam dolore, neque mollitia labore quibusdam in enim praesentium omnis illum. Architecto eaque expedita deserunt nobis recusandae ut voluptatibus iusto? Facilis sequi reiciendis eveniet, reprehenderit eos sunt culpa alias velit nisi qui ipsum dolores numquam, quas in quia vero? Corrupti minima illum maiores exercitationem quia blanditiis impedit eius? Beatae odit deleniti expedita corrupti provident perferendis quae necessitatibus corporis harum delectus. Mollitia modi beatae quod architecto hic explicabo doloribus, aliquam voluptates aliquid, labore nulla assumenda molestiae ex officiis voluptate, ullam similique totam quis quae vitae id eaque?
        </Text>
        <Text className='text-green-600'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero nesciunt laudantium obcaecati, facilis maxime ex consectetur rerum ea exercitationem assumenda voluptas facere quia ipsam soluta omnis ullam fuga, quam ut! Repudiandae totam dolore, neque mollitia labore quibusdam in enim praesentium omnis illum. Architecto eaque expedita deserunt nobis recusandae ut voluptatibus iusto? Facilis sequi reiciendis eveniet, reprehenderit eos sunt culpa alias velit nisi qui ipsum dolores numquam, quas in quia vero? Corrupti minima illum maiores exercitationem quia blanditiis impedit eius? Beatae odit deleniti expedita corrupti provident perferendis quae necessitatibus corporis harum delectus. Mollitia modi beatae quod architecto hic explicabo doloribus, aliquam voluptates aliquid, labore nulla assumenda molestiae ex officiis voluptate, ullam similique totam quis quae vitae id eaque? </Text>
    </View>

  )
}

export default Home